### ISSUE TITLE
LineEdit placeholder won't stay when playing the scene.

### ISSUE THREAD

**Issue by ghost** [moritztim/Godot-Form#6]
LineEdit placeholder won't stay when playing the scene. I recorded a video showing the problem.
I only succeeded creating a placeholder for the given input creating another Label like in the screenshot.

Anyways, Thanks so much for the useful godot plugin!

[simplescreenrecorder-2024-02-09_19.05.43.webm](https://github.com/moritz-t-w/Godot-Form/assets/62967229/f1356d23-06aa-44f4-a12f-247bfc515f05)

![image](https://github.com/moritz-t-w/Godot-Form/assets/62967229/8a209122-f1f2-424d-a594-f29af9b7fa84)

**Comment by moritztim** [comment]
Hmm... `FormLabel` might be interfering with your placeholder, I wrote some ugly code related to placeholders & labels. Please show me the properties of the labels

Thanks, I'm honored that someone is using my plugin :D I like your form design

**Comment by ghost** [comment]
Hello, thanks for replying!

I'll provide some screenshots.

Your plugin has some potential! I really like the "Protocols" concept and all the validation system ofc.

![image](https://github.com/moritz-t-w/Godot-Form/assets/62967229/f010e6b1-5ba7-4b2e-b586-987de678727d)

**Comment by moritztim** [comment]
Ok this is definitely not even expected misbehavior. I'll look into it.

**Comment by moritztim** [comment]
As a workaround I suggest changing the label's text to the text of your placeholder and then changing the label display mode to "Separate"
![screenshot](https://github.com/moritz-t-w/Godot-Form/assets/90388353/484ba897-3218-418a-ac48-3fd4bf1b3f81)
Now just add another label (not FormLabel) to label the field

**Comment by ghost** [comment]
Fixed by https://github.com/moritz-t-w/Godot-Form/pull/7

**Comment by moritztim** [comment]
I have made a new release and submitted an edit to the Asset Library. It'll probably be up by the end of the week
